import { useState, useEffect, useRef } from 'react';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import QRCode from 'qrcode';
import { Download, Printer, MessageSquare, Mail, X } from 'lucide-react';
import { Vehicle, VehicleAPI } from '@/services/vehicleApi';
import { Location } from '@/services/locationApi';
import { formatDateTime } from '@/utils/dateUtils';
import { useToast } from '@/hooks/use-toast';
import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';

interface QRTicketDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  vehicle: Vehicle | null;
  location: Location | null;
  gateName?: string;
}

export function QRTicketDialog({ open, onOpenChange, vehicle, location, gateName }: QRTicketDialogProps) {
  const [qrData, setQrData] = useState<string>('');
  const [qrImageUrl, setQrImageUrl] = useState<string>('');
  const [otp, setOtp] = useState<string>('');
  const qrCanvasRef = useRef<HTMLCanvasElement>(null);
  const { toast } = useToast();

  useEffect(() => {
    if (vehicle && location) {
      // Use OTP from database (generated by backend during check-in)
      const fetchVehicleOTP = async () => {
        try {
          // Get OTP from vehicle object (key is "otp")
          let vehicleOTP = vehicle.otp;
          
          // Debug: Log vehicle object to see what fields are available
          console.log('Vehicle object for QR:', vehicle);
          console.log('OTP from vehicle:', vehicleOTP);
          
          // If OTP is not in the vehicle object, try to fetch it from backend
          if (!vehicleOTP && vehicle.id) {
            console.log('OTP not found in vehicle object, fetching from backend...');
            try {
              const fetchedVehicle = await VehicleAPI.getVehicleById(vehicle.id);
              vehicleOTP = fetchedVehicle.otp;
              console.log('OTP from fetched vehicle:', vehicleOTP);
            } catch (fetchError) {
              console.error('Error fetching vehicle OTP:', fetchError);
            }
          }
          
          // If OTP is still not available, show error
          if (!vehicleOTP) {
            console.error('OTP not found in vehicle data. Vehicle object:', vehicle);
            toast({
              variant: "destructive",
              title: "OTP Missing",
              description: "OTP not found for this vehicle. Please check in again or contact support.",
            });
            return;
          }
          
          setOtp(vehicleOTP);

          // Build human-readable receipt text for QR with clear formatting
          const checkInTime = formatDateTime(new Date(vehicle.check_in_time));
          const locationName = location.locations_name || location.address;
          
          let dataString = `PARKFLOW PARKING TICKET
================================

TICKET INFORMATION
--------------------------------
Ticket ID: ${vehicle.id}
Plate Number: ${vehicle.plate_number}
Vehicle Type: ${vehicle.vehicle_type}
Check-in Time: ${checkInTime}
Location: ${locationName}
Gate: ${gateName || 'Main Gate'}
Status: ${vehicle.status || 'checked_in'}

SECURITY CODE
--------------------------------
OTP: ${vehicleOTP}

ADDITIONAL DETAILS
--------------------------------`;

          if (location.address && location.address !== locationName) {
            dataString += `\nAddress: ${location.address}`;
          }
          if (vehicle.mobile_number) {
            dataString += `\nMobile: ${vehicle.mobile_number}`;
          }
          if (vehicle.session_id) {
            dataString += `\nSession ID: ${vehicle.session_id}`;
          }

          dataString += `\n
================================
Please keep this ticket safe
Show QR code at checkout
Generated by ParkFlow System`;
          
          // Debug: Log the data being encoded
          console.log('QR Code Data:', dataString);
          setQrData(dataString);

          // Generate QR code image with high quality and error correction
          QRCode.toDataURL(dataString, {
            width: 300,
            margin: 3,
            errorCorrectionLevel: 'H', // High error correction for better scanning
            color: {
              dark: '#000000',
              light: '#FFFFFF'
            },
            type: 'image/png',
            quality: 1.0
          }).then(url => {
            setQrImageUrl(url);
            console.log('QR Code generated successfully');
          }).catch(err => {
            console.error('Error generating QR code:', err);
          });
        } catch (error) {
          console.error('Error in fetchVehicleOTP:', error);
        }
      };

      fetchVehicleOTP();
    }
  }, [vehicle, location, gateName, toast]);

  const handleDownloadPDF = async () => {
    if (!vehicle || !location) return;

    const ticketElement = document.getElementById('qr-ticket-content');
    if (!ticketElement) return;

    try {
      const canvas = await html2canvas(ticketElement, {
        scale: 2,
        backgroundColor: '#ffffff',
        useCORS: true
      });

      const imgData = canvas.toDataURL('image/png');
      const pdf = new jsPDF('p', 'mm', [80, 200]); // 80mm width (thermal printer size)
      
      const imgWidth = 80;
      const pageHeight = pdf.internal.pageSize.height;
      const imgHeight = (canvas.height * imgWidth) / canvas.width;
      let heightLeft = imgHeight;
      let position = 0;

      pdf.addImage(imgData, 'PNG', 0, position, imgWidth, imgHeight);
      heightLeft -= pageHeight;

      while (heightLeft >= 0) {
        position = heightLeft - imgHeight;
        pdf.addPage();
        pdf.addImage(imgData, 'PNG', 0, position, imgWidth, imgHeight);
        heightLeft -= pageHeight;
      }

      pdf.save(`Parking-Ticket-${vehicle.plate_number}-${Date.now()}.pdf`);
    } catch (error) {
      console.error('Error generating PDF:', error);
    }
  };

  const handleDownloadPNG = async () => {
    if (!vehicle || !location) return;

    const ticketElement = document.getElementById('qr-ticket-content');
    if (!ticketElement) return;

    try {
      const canvas = await html2canvas(ticketElement, {
        scale: 2,
        backgroundColor: '#ffffff',
        useCORS: true
      });

      const link = document.createElement('a');
      link.download = `Parking-Ticket-${vehicle.plate_number}-${Date.now()}.png`;
      link.href = canvas.toDataURL('image/png');
      link.click();
    } catch (error) {
      console.error('Error generating PNG:', error);
    }
  };

  const handlePrint = () => {
    const ticketElement = document.getElementById('qr-ticket-content');
    if (!ticketElement) return;

    const printWindow = window.open('', '_blank');
    if (!printWindow) return;

    printWindow.document.write(`
      <!DOCTYPE html>
      <html>
        <head>
          <title>Parking Ticket</title>
          <style>
            @page {
              size: 80mm auto;
              margin: 5mm;
            }
            body {
              font-family: 'Courier New', monospace;
              margin: 0;
              padding: 10px;
              font-size: 12px;
            }
            .ticket {
              width: 100%;
              max-width: 80mm;
            }
            .header {
              text-align: center;
              font-weight: bold;
              font-size: 16px;
              margin-bottom: 10px;
            }
            .qr-code {
              text-align: center;
              margin: 15px 0;
            }
            .info-row {
              display: flex;
              justify-content: space-between;
              margin: 5px 0;
              padding: 3px 0;
              border-bottom: 1px dashed #ccc;
            }
            .label {
              font-weight: bold;
            }
            .footer {
              text-align: center;
              margin-top: 15px;
              font-size: 10px;
              color: #666;
            }
          </style>
        </head>
        <body>
          ${ticketElement.innerHTML}
        </body>
      </html>
    `);
    printWindow.document.close();
    printWindow.focus();
    setTimeout(() => {
      printWindow.print();
      printWindow.close();
    }, 250);
  };

  const handleWhatsAppShare = () => {
    if (!vehicle || !location) return;

    const message = `🚗 *Parking Ticket - ParkFlow*\n\n` +
      `Plate Number: ${vehicle.plate_number}\n` +
      `Vehicle Type: ${vehicle.vehicle_type}\n` +
      `Check-in Time: ${formatDateTime(new Date(vehicle.check_in_time))}\n` +
      `Location: ${location.locations_name || location.address}\n` +
      `Gate: ${gateName || 'Main Gate'}\n` +
      `Ticket ID: ${vehicle.id}\n` +
      (otp ? `OTP: *${otp}*\n` : '') +
      `\nPlease keep this ticket safe for checkout.`;

    const whatsappUrl = `https://wa.me/?text=${encodeURIComponent(message)}`;
    window.open(whatsappUrl, '_blank');
  };

  const handleSMSShare = () => {
    if (!vehicle || !location || !vehicle.mobile_number) return;

    const message = `ParkFlow Parking Ticket\n\n` +
      `Plate: ${vehicle.plate_number}\n` +
      `Type: ${vehicle.vehicle_type}\n` +
      `Check-in: ${formatDateTime(new Date(vehicle.check_in_time))}\n` +
      `Location: ${location.locations_name || location.address}\n` +
      `Gate: ${gateName || 'Main Gate'}\n` +
      `Ticket ID: ${vehicle.id}\n` +
      (otp ? `OTP: ${otp}\n` : '') +
      `\nKeep this ticket safe for checkout.`;

    const smsUrl = `sms:${vehicle.mobile_number}?body=${encodeURIComponent(message)}`;
    window.location.href = smsUrl;
  };

  if (!vehicle || !location) return null;

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-md w-[95vw] sm:w-full">
        <DialogHeader>
          <DialogTitle className="text-xl sm:text-2xl font-bold">Parking Ticket</DialogTitle>
          <DialogDescription className="text-sm">
            Your QR code parking ticket has been generated
          </DialogDescription>
        </DialogHeader>

        <div id="qr-ticket-content" className="bg-white p-4 rounded-lg border-2 border-dashed border-gray-300">
          {/* Header */}
          <div className="text-center mb-4">
            <h2 className="text-lg font-bold">PARKFLOW</h2>
            <p className="text-sm text-gray-600">Parking Ticket</p>
          </div>

          {/* QR Code */}
          <div className="flex justify-center my-4">
            {qrImageUrl && (
              <div className="bg-white p-3 rounded border-2 border-gray-400">
                <img 
                  src={qrImageUrl} 
                  alt="QR Code" 
                  className="w-[250px] h-[250px] sm:w-[300px] sm:h-[300px]" 
                  style={{ imageRendering: 'crisp-edges' }}
                />
              </div>
            )}
          </div>

          {/* Ticket Information */}
          <div className="space-y-2 text-sm">
            <div className="flex justify-between border-b border-dashed pb-1">
              <span className="font-semibold">Plate Number:</span>
              <span>{vehicle.plate_number}</span>
            </div>
            <div className="flex justify-between border-b border-dashed pb-1">
              <span className="font-semibold">Vehicle Type:</span>
              <span>{vehicle.vehicle_type}</span>
            </div>
            <div className="flex justify-between border-b border-dashed pb-1">
              <span className="font-semibold">Check-in Time:</span>
              <span className="text-xs">{formatDateTime(new Date(vehicle.check_in_time))}</span>
            </div>
            <div className="flex justify-between border-b border-dashed pb-1">
              <span className="font-semibold">Location:</span>
              <span className="text-xs">{location.locations_name || location.address}</span>
            </div>
            {gateName && (
              <div className="flex justify-between border-b border-dashed pb-1">
                <span className="font-semibold">Gate:</span>
                <span>{gateName}</span>
              </div>
            )}
            <div className="flex justify-between border-b border-dashed pb-1">
              <span className="font-semibold">Ticket ID:</span>
              <span className="text-xs font-mono">{vehicle.id.slice(0, 8)}...</span>
            </div>
            {otp && (
              <div className="flex justify-between border-b border-dashed pb-1 bg-yellow-50 -mx-4 px-4 py-2 mt-2">
                <span className="font-bold text-base">OTP:</span>
                <span className="text-lg font-mono font-bold text-blue-600">{otp}</span>
              </div>
            )}
          </div>

          {/* Footer */}
          <div className="text-center mt-4 text-xs text-gray-500">
            <p>Please keep this ticket safe</p>
            <p>Show QR code at checkout</p>
          </div>
        </div>

        {/* Action Buttons */}
        <div className="flex flex-wrap gap-2 mt-4">
          <Button
            onClick={handlePrint}
            variant="outline"
            className="flex-1 min-w-[120px]"
          >
            <Printer className="h-4 w-4 mr-2" />
            Print
          </Button>
          <Button
            onClick={handleDownloadPDF}
            variant="outline"
            className="flex-1 min-w-[120px]"
          >
            <Download className="h-4 w-4 mr-2" />
            PDF
          </Button>
          <Button
            onClick={handleDownloadPNG}
            variant="outline"
            className="flex-1 min-w-[120px]"
          >
            <Download className="h-4 w-4 mr-2" />
            PNG
          </Button>
          <Button
            onClick={handleWhatsAppShare}
            variant="outline"
            className="flex-1 min-w-[120px]"
          >
            <MessageSquare className="h-4 w-4 mr-2" />
            WhatsApp
          </Button>
          {vehicle.mobile_number && (
            <Button
              onClick={handleSMSShare}
              variant="outline"
              className="flex-1 min-w-[120px]"
            >
              <Mail className="h-4 w-4 mr-2" />
              SMS
            </Button>
          )}
        </div>

        <div className="flex justify-end mt-4">
          <Button onClick={() => onOpenChange(false)} variant="ghost">
            Close
          </Button>
        </div>
      </DialogContent>
    </Dialog>
  );
}

