// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bvpdjeknzhclpriisfeh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ2cGRqZWtuemhjbHByaWlzZmVoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxNjUwNzYsImV4cCI6MjA3Mjc0MTA3Nn0.Bv7ye97wldyhhxvjCC8VidkdrIZFi0Xsu8Fq42fSka8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});